# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-02 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('deleted', models.BooleanField()),
                ('added_on', models.DateTimeField()),
                ('available_date', models.DateField()),
            ],
        ),
    ]
